# Generated by Django 5.1.1 on 2024-10-08 16:58

import django.core.validators
import module.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('user_phone_number', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField(default=module.models.current_timestamp, editable=False)),
                ('user_password', models.CharField(default='default_password', max_length=56)),
            ],
        ),
    ]
