# Generated by Django 5.1.1 on 2024-09-30 11:58

import module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='timestamp',
            field=models.BigIntegerField(default=module.models.current_timestamp),
        ),
    ]
