# Generated by Django 5.1.1 on 2024-10-08 15:08

import django.db.models.deletion
import module.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(default='default_password', max_length=56),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_heading', models.CharField(blank=True, max_length=255)),
                ('note_body', models.TextField()),
                ('created_at_timestamp', models.BigIntegerField(default=module.models.current_timestamp, editable=False)),
                ('updated_at_timestamp', models.BigIntegerField(default=module.models.current_timestamp)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='module.usermodel')),
            ],
        ),
    ]
