<<<<<<< HEAD:NeverNote/module/migrations/0002_usermodel_timestamp_alter_usermodel_user_email.py
# Generated by Django 5.1.1 on 2024-10-01 18:16
=======
# Generated by Django 5.1.1 on 2024-09-30 11:58
>>>>>>> main:NeverNote/module/migrations/0002_alter_usermodel_timestamp.py

import module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='timestamp',
            field=models.BigIntegerField(default=module.models.current_timestamp),
        ),
    ]
