# Generated by Django 5.1.1 on 2024-10-01 18:16

import django.core.validators
import module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='timestamp',
            field=models.BigIntegerField(default=module.models.current_timestamp, editable=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
