# Generated by Django 5.1.1 on 2024-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='post_note_global',
            field=models.BooleanField(default=False),
        ),
    ]
