# Generated by Django 5.1.1 on 2024-10-22 13:37

import module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_notesmodel_post_note_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='updated_at_timestamp',
            field=models.BigIntegerField(default=module.models.current_timestamp, editable=False),
        ),
    ]
