<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-01 18:17
=======
# Generated by Django 5.1.1 on 2024-09-30 11:58
>>>>>>> main

import module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('module', '0002_usermodel_timestamp_alter_usermodel_user_email'),
=======
        ('module', '0002_alter_usermodel_timestamp'),
>>>>>>> main
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='timestamp',
<<<<<<< HEAD
            field=models.BigIntegerField(default=module.models.current_timestamp),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_password',
            field= models.CharField(max_length=25),
=======
            field=models.BigIntegerField(default=module.models.current_timestamp, editable=False),
>>>>>>> main
        ),
    ]
