# Generated by Django 5.1.1 on 2024-10-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_usermodel_user_password_alter_usermodel_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
