# Generated by Django 5.1.1 on 2024-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_usermodel_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
