# Generated by Django 5.1.1 on 2024-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
