# Generated by Django 5.1.1 on 2024-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_alter_usermodel_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(default='default_password', max_length=56),
        ),
    ]
