# Generated by Django 5.1.1 on 2024-10-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_alter_usermodel_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
